import type { Metadata } from "next";
import { ArrowUpRight, Check, CreditCard, Download } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export const metadata: Metadata = { title: "Billing" };

export default function BillingPage() {
  return <div className="space-y-8"><PageHeader eyebrow="Pro plan" title="Billing" description="Manage your subscription, payment method, and invoices for Acme Studio." action={<Button>Manage subscription <ArrowUpRight /></Button>} /><div className="grid gap-4 xl:grid-cols-[1.4fr_1fr]"><Card className="relative overflow-hidden"><div className="surface-grid pointer-events-none absolute inset-0 opacity-60" /><CardContent className="relative"><Badge variant="success"><Check className="size-3" /> Active plan</Badge><p className="mt-8 text-3xl font-[650] tracking-[-0.04em]">Pro</p><p className="mt-2 text-sm text-muted-foreground">Everything your team needs to operate at scale.</p><div className="mt-8 flex items-end gap-2"><span className="text-4xl font-[650] tracking-[-0.04em]">€149</span><span className="pb-1 text-sm text-muted-foreground">per month</span></div><p className="mt-3 text-xs text-muted-foreground">Renews on November 1, 2026 · VAT calculated at checkout</p></CardContent></Card><Card><CardHeader><CardTitle>Payment method</CardTitle></CardHeader><CardContent><div className="flex items-center gap-3 rounded-lg border bg-muted/50 p-4"><span className="grid size-10 place-items-center rounded-lg bg-card"><CreditCard className="size-4" /></span><div><p className="text-sm font-[600]">Visa ending in 4242</p><p className="mt-0.5 text-xs text-muted-foreground">Expires 08/29</p></div></div><Button variant="secondary" className="mt-4 w-full">Update payment method</Button></CardContent></Card></div><Card><CardHeader><div><CardTitle>Invoices</CardTitle><p className="mt-1 text-sm text-muted-foreground">Receipts for your workspace subscription</p></div></CardHeader><div className="divide-y">{[["INV-2026-09", "Oct 1, 2026", "€149.00"], ["INV-2026-08", "Sep 1, 2026", "€149.00"], ["INV-2026-07", "Aug 1, 2026", "€149.00"]].map(([id, date, total]) => <div key={id} className="flex items-center gap-4 px-5 py-4 text-sm"><span className="font-mono text-xs font-semibold">{id}</span><span className="text-muted-foreground">{date}</span><span className="ml-auto font-mono text-xs">{total}</span><Badge variant="success">Paid</Badge><Button variant="ghost" size="icon" aria-label={`Download invoice ${id}`}><Download /></Button></div>)}</div></Card></div>;
}
